### ISSUE TITLE
Any chance for part3?

### ISSUE THREAD

**Issue by tomasz-sobczyk-wttech** [JimmyDqv/self-hosted-runners-on-aws#1]
Hi @JimmyDqv, any chance for part3?

**Comment by JimmyDqv** [comment]
@tomasz-sobczyk-wttech Yes. I need to find the time to finish it. Sorry for the delay.

**Comment by Chalong81** [comment]
chalongthonghan81@gmail.com

**Comment by JimmyDqv** [comment]
Part 3 is on it's way. Almost completed.

**Comment by JimmyDqv** [comment]
Added!
